/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2023-05-09 01:40:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \t<div class=\"form-group\" style=\"width: 38%; margin: 10px auto;\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t<button type=\"button\" class=\"btn btn-primary btn-lg btn-block\" -->\r\n");
      out.write("<!-- \t\t\tonclick=\"weather()\">보내기</button> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<h2 style=\"text-align: center;\">20230509 날씨</h2>\r\n");
      out.write("\t\t\t<table\r\n");
      out.write("\t\t\t\tstyle=\"border-collapse: collapse; margin: auto; text-align: center; height: 300px; width: 1500px;\">\r\n");
      out.write("\t\t\t\t<tr style=\"border: 1px solid #9e9e9e82;\">\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">시간(H)</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">06</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">07</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">08</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">09</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">10</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">11</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">12</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">13</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">14</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">15</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">16</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">17</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">18</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">19</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">20</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">21</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">22</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">23</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"border: 1px solid #9e9e9e82;\">\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">기온(℃)</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">11</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">12</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">14</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">17</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">19</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">21</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">22</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">23</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">24</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">23</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">23</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">22</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">20</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">19</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">17</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">16</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">15</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">14</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"border: 1px solid #9e9e9e82;\">\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">풍향(deg)</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">200</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">207</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">231</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">243</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">253</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">255</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">253</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">252</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">253</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">252</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">248</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">245</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">239</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">232</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">218</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">209</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">239</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">248</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"border: 1px solid #9e9e9e82;\">\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">풍속(m/s)</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">1.2</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0.9</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">1.4</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">2</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">2.4</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">2.8</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">3</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">3.3</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">3.4</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">3.5</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">3.5</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">3.1</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">2.7</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">1.8</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">1.1</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">1</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">1.2</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0.5</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"border: 1px solid #9e9e9e82;\">\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">하늘상태</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">맑음</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"border: 1px solid #9e9e9e82;\">\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">강수확률(%)</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"border: 1px solid #9e9e9e82;\">\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">강수량(mm)</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">0</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"border: 1px solid #9e9e9e82;\">\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">습도(%)</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">80</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">70</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">65</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">60</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">55</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">45</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">40</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">35</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">35</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">35</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">40</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">40</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">45</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">55</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">60</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">70</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">75</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"border: 1px solid #9e9e9e82;\">75</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- \t</div> -->\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function weather() {\r\n");
      out.write("    jQuery.ajax({\r\n");
      out.write("        url : \"/api/weather\",\r\n");
      out.write("        type : \"get\",\r\n");
      out.write("        timeout: 30000,\r\n");
      out.write("        contentType: \"application/json\",\r\n");
      out.write("        dataType : \"json\",\r\n");
      out.write("        success : function(data, status, xhr) {\r\n");
      out.write("\r\n");
      out.write("            let dataHeader = data.result.response.header.resultCode;\r\n");
      out.write("\r\n");
      out.write("            if (dataHeader == \"00\") {\r\n");
      out.write("               console.log(\"success == >\");\r\n");
      out.write("               console.log(data.result.response.body.items);\r\n");
      out.write("            } else {\r\n");
      out.write("               console.log(\"fail == >\");\r\n");
      out.write("               console.log(data);               \r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error : function(e, status, xhr, data) {\r\n");
      out.write("            console.log(\"error == >\");\r\n");
      out.write("            console.log(e);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
